# Single GPU training t5-xxl using LoRA
model: meta-llama/Meta-Llama-3-70B
tokenizer: meta-llama/Meta-Llama-3-70B
model_name: /scratch/qmei_root/qmei/xziyang/huggingface/models--meta-llama--Meta-Llama-3-70B-Instruct/snapshots/7129260dd854a80eb10ace5f61c20324b472b31c
enable_fsdp: True
use_peft: True
peft_method: lora
use_wandb: True
save_model: True
dist_checkpoint_root_folder: model_checkpoints
dist_checkpoint_folder: fine-tuned
fsdp_config.pure_bf16: True
output_dir: /scratch/qmei_root/qmei/xziyang/model_ckpt
max_eval_step: 100
dataset: alpaca_dataset
data_path: llm4explore/model/src/llama_recipes/datasets/alpaca_data.json
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_train: [1975, 2023]
  time_val: [2022, 2023]
  time_test: [2023, 2024]
  use_sampler: True
  sampler_kwargs:
    k_max: 3
  input_kwargs: null
  num_test: 100
embeddings:
  path: data/ada2_key_ideas.npz
training_args:
  learning_rate: 0.0002
  output_dir: /scratch/qmei_root/qmei/xziyang/hf_checkpoints/llama3-70b-query-and-ref/lora_8/
  eval_strategy: steps
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  predict_with_generate: True
  logging_steps: 100
  save_steps: 10000
  eval_steps: 100
  warmup_steps: 2000
  save_total_limit: 1
  num_train_epochs: 3
  report_to: wandb
  generation_max_length: 64
  run_name: t5-xxl-query-and-ref
  bf16: True
wandb_args:
  project: idea_generation
  group: t5-xxl
  name: Llama-3-70B-Instruct
lora_args:
  r: 8
  lora_alpha: 16
  target_modules: [q, v]
  lora_dropout: 0.05
  task_type: SEQ_2_SEQ_LM
metrics: [bleu, rouge, meteor, cosine]
